# Generated by Django 6.0.2 on 2026-03-01 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rarity', models.IntegerField(default=5)),
                ('job', models.CharField(max_length=50)),
                ('weapon_type', models.CharField(default='Unknown', max_length=50)),
                ('element', models.CharField(max_length=100)),
                ('is_released', models.BooleanField(default=True)),
                ('hp_120', models.IntegerField(default=0)),
                ('sp_120', models.IntegerField(default=0)),
                ('p_atk_120', models.IntegerField(default=0)),
                ('p_def_120', models.IntegerField(default=0)),
                ('e_atk_120', models.IntegerField(default=0)),
                ('e_def_120', models.IntegerField(default=0)),
                ('crit_120', models.IntegerField(default=0)),
                ('spd_120', models.IntegerField(default=0)),
                ('p_dps', models.CharField(default='C', max_length=5)),
                ('e_dps', models.CharField(default='C', max_length=5)),
                ('tankiness', models.CharField(default='C', max_length=5)),
                ('healer', models.CharField(default='C', max_length=5)),
                ('buffer', models.CharField(default='C', max_length=5)),
                ('debuffer', models.CharField(default='C', max_length=5)),
                ('breaker', models.CharField(default='C', max_length=5)),
                ('damage_coverage', models.IntegerField(default=0)),
                ('total_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'travelers_master',
                'managed': False,  # ← CLAVE: Django no toca esta tabla
            },
        ),
        migrations.CreateModel(
            name='RosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_obtained', models.BooleanField(default=False)),
                ('is_6_stars', models.BooleanField(default=False)),
                ('current_level', models.IntegerField(default=1)),
                ('awakening_level', models.IntegerField(default=0)),
                ('ultimate_level', models.IntegerField(default=0)),
                ('is_ultimate_awakened', models.BooleanField(default=False)),
                ('has_ultimate_overcharge', models.BooleanField(default=False)),
                ('lantern_blessing_active', models.BooleanField(default=False)),
                ('bless_hp', models.IntegerField(default=0)),
                ('bless_sp', models.IntegerField(default=0)),
                ('bless_p_atk', models.IntegerField(default=0)),
                ('bless_p_def', models.IntegerField(default=0)),
                ('bless_e_atk', models.IntegerField(default=0)),
                ('bless_e_def', models.IntegerField(default=0)),
                ('bless_crit', models.IntegerField(default=0)),
                ('bless_spd', models.IntegerField(default=0)),
                ('current_weapon', models.CharField(blank=True, max_length=100, null=True)),
                ('weapon_souls_count', models.IntegerField(default=0)),
                ('current_armor', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('traveler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entry', to='api.traveler')),
            ],
            options={
                'db_table': 'roster_entries',
            },
        ),
    ]
