# Generated by Django 6.0.2 on 2026-03-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_a4', models.BooleanField(default=False)),
                ('p_atk', models.IntegerField(default=0)),
                ('e_atk', models.IntegerField(default=0)),
                ('p_def', models.IntegerField(default=0)),
                ('e_def', models.IntegerField(default=0)),
                ('spd', models.IntegerField(default=0)),
                ('crit', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('sp', models.IntegerField(default=0)),
                ('extra', models.TextField(default='')),
            ],
            options={
                'db_table': 'accessories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('armor_type', models.CharField(max_length=20)),
                ('p_def', models.IntegerField(default=0)),
                ('e_def', models.IntegerField(default=0)),
                ('p_atk', models.IntegerField(default=0)),
                ('e_atk', models.IntegerField(default=0)),
                ('spd', models.IntegerField(default=0)),
                ('crit', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('sp', models.IntegerField(default=0)),
                ('extra', models.TextField(default='')),
            ],
            options={
                'db_table': 'armors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hp', models.IntegerField(default=0)),
                ('p_atk', models.IntegerField(default=0)),
                ('e_atk', models.IntegerField(default=0)),
                ('p_def', models.IntegerField(default=0)),
                ('e_def', models.IntegerField(default=0)),
                ('spd', models.IntegerField(default=0)),
                ('crit', models.IntegerField(default=0)),
                ('skill_name', models.CharField(default='', max_length=100)),
                ('skill_effect', models.TextField(default='')),
            ],
            options={
                'db_table': 'pets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('weapon_type', models.CharField(choices=[('Sword', 'Sword'), ('Dagger', 'Dagger'), ('Axe', 'Axe'), ('Bow', 'Bow'), ('Staff', 'Staff'), ('Polearm', 'Polearm'), ('Tome', 'Tome'), ('Fan', 'Fan')], max_length=20)),
                ('series', models.CharField(default='', max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('p_atk', models.IntegerField(default=0)),
                ('e_atk', models.IntegerField(default=0)),
                ('p_def', models.IntegerField(default=0)),
                ('e_def', models.IntegerField(default=0)),
                ('spd', models.IntegerField(default=0)),
                ('crit', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('sp', models.IntegerField(default=0)),
                ('extra', models.TextField(default='')),
                ('slot_count', models.IntegerField(default=0)),
                ('soul_bonus_1', models.CharField(blank=True, max_length=20, null=True)),
                ('soul_bonus_2', models.CharField(blank=True, max_length=20, null=True)),
                ('soul_bonus_3', models.CharField(blank=True, max_length=20, null=True)),
                ('soul_bonus_4', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'weapons',
                'managed': False,
            },
        ),
    ]
