# Generated by Django 6.0.2 on 2026-06-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_accessory_exclusive_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('accessory', 'Accessory')], max_length=20)),
                ('item_name', models.CharField(max_length=150)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_items',
                'ordering': ['item_type', 'item_name'],
                'unique_together': {('item_type', 'item_name')},
            },
        ),
    ]
