# Generated by Django 6.0.2 on 2026-06-03 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_accessory_is_artifact'),
    ]

    operations = [
    ]
