# Generated by Django 6.0.2 on 2026-06-04 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_accessory_imprint_req'),
    ]

    operations = [
    ]
