# Generated by Django 6.0.2 on 2026-06-05 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_accessory_source'),
    ]

    operations = [
    ]
